# LLM Minutes generation
import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def generate_minutes(transcript: str, meeting_title: str = "Meeting") -> str:
    """
    Takes the full meeting transcript and returns structured meeting minutes
    as a markdown-formatted string, generated by Llama 3 via Groq.

    Parameters:
        transcript    : the complete transcribed text of the meeting
        meeting_title : optional title for the meeting
    """

    # This is the prompt we send to Llama 3.
    # The quality of your minutes depends heavily on how well this prompt is written
    # We're being very specific about the format we want back
    prompt = f"""
You are a professional minute writer for formal meetings in Ghana.
Below is a raw transcript of a meeting. Your job is to write clean, structured meeting minutes from it.

Follow this exact format:

# {meeting_title}

**Date:** [extract from transcript if mentioned, otherwise write "Not stated"]
**Time:** [extract if mentioned, otherwise "Not stated"]  
**Location:** [extract if mentioned, otherwise "Not stated"]

## Attendees
[List names and roles if mentioned. If not mentioned, write "Not recorded"]

## Agenda
[List agenda items discussed]

## Discussions & Key Points
[Summarize the main points discussed, organized clearly]

## Decisions Made
[List every decision that was agreed upon]

## Action Items
[List tasks assigned, who is responsible, and deadlines if mentioned]

## Next Meeting
[If mentioned, state when. Otherwise write "Not stated"]

---
*Minutes prepared by G-Minute Writer*

---

Here is the meeting transcript:

\"\"\"{transcript}\"\"\"

Write the minutes now. Be formal, concise, and accurate. Do not invent information not present in the transcript.
"""
    
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",   # Groq's most capable free model
        messages=[
            {
                "role": "system",
                "content": "Your are a professional minute writer. You write formal, accurate meeting minutes from transcripts."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.1,   # Low temperature = more focused, less creative = better formal docs
        max_tokens=2048,
    )

    content = response.choices[0].message.content

    if not content or content.strip() == "":
        return f"# {meeting_title}\n\n## Summary\nMinutes could not be generated.\n\nTranscript:\n{transcript}"
    return content.strip()