const PDFDocument = require("pdfkit");

/**
 * Takes the minutes text (markdown-ish format from Llama 3)
 * and generates a clean PDF buffer we can send to the frontend.
 *
 * @param {string} minutesText - the formatted minutes from the AI
 * @param {string} meetingTitle - used in the PDF header
 * @returns {Promise<Buffer>} PDF file as a buffer
 */
function generatePDF(minutesText, meetingTitle = "Meeting") {
  return new Promise((resolve, reject) => {
    // ✅ Guard against null or empty minutes text
    // Without this, minutesText.split("\n") crashes with
    // "Cannot read properties of null (reading 'split')"
    if (!minutesText || typeof minutesText !== "string" || minutesText.trim() === "") {
      minutesText = `# ${meetingTitle}\n\n## Notice\nThe AI was unable to generate minutes for this transcript.\nPlease try again with a longer or clearer recording.`;
    }
    
    // Create a new PDF document
    const doc = new PDFDocument({
      margin: 50,
      size: "A4",
    });

    // We collect the PDF data chunks into an array, then combine at the end
    // PDFKit works as a stream — it outputs data in pieces
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ── HEADER ──────────────────────────────────────────────
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("MEETING MINUTES", { align: "center" });

    doc.moveDown(0.5);

    doc
      .fontSize(14)
      .font("Helvetica")
      .text(meetingTitle, { align: "center" });

    doc.moveDown(0.5);

    // A horizontal line under the header
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#333333")
      .lineWidth(1)
      .stroke();

    doc.moveDown(1);

    // ── BODY — Parse the markdown-like text from Llama 3 ────
    // We go line by line and apply formatting based on markdown symbols
    const lines = minutesText.split("\n");

    lines.forEach((line) => {
      const trimmed = line.trim();

      if (trimmed.startsWith("# ")) {
        // H1 heading — skip it, we already put the title in the header
        return;
      } else if (trimmed.startsWith("## ")) {
        // H2 heading — section titles like "Attendees", "Decisions Made"
        doc.moveDown(0.8);
        doc
          .fontSize(13)
          .font("Helvetica-Bold")
          .fillColor("#1a1a1a")
          .text(trimmed.replace("## ", "").toUpperCase());

        // Underline effect using a thin line
        doc
          .moveTo(50, doc.y + 2)
          .lineTo(545, doc.y + 2)
          .strokeColor("#cccccc")
          .lineWidth(0.5)
          .stroke();

        doc.moveDown(0.3);
      } else if (trimmed.startsWith("**") && trimmed.endsWith("**")) {
        // Bold line e.g. **Date:** ...
        doc
          .fontSize(11)
          .font("Helvetica-Bold")
          .fillColor("#333333")
          .text(trimmed.replace(/\*\*/g, ""));
      } else if (trimmed.startsWith("**") && trimmed.includes(":**")) {
        // Bold label with value e.g. **Date:** 12th January
        const parts = trimmed.split(":**");
        const label = parts[0].replace("**", "") + ":";
        const value = parts[1]?.trim() || "";

        doc.fontSize(11).font("Helvetica-Bold").fillColor("#333333");
        // Write label inline, then continue with normal text
        doc.text(label + " ", { continued: true });
        doc.font("Helvetica").fillColor("#444444").text(value);
      } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        // Bullet points
        doc
          .fontSize(11)
          .font("Helvetica")
          .fillColor("#444444")
          .text("•  " + trimmed.slice(2), {
            indent: 15,
            lineGap: 3,
          });
      } else if (trimmed.startsWith("---")) {
        // Horizontal rule
        doc.moveDown(0.5);
        doc
          .moveTo(50, doc.y)
          .lineTo(545, doc.y)
          .strokeColor("#eeeeee")
          .lineWidth(0.5)
          .stroke();
        doc.moveDown(0.5);
      } else if (trimmed === "") {
        // Empty line — small vertical space
        doc.moveDown(0.4);
      } else {
        // Regular paragraph text
        doc
          .fontSize(11)
          .font("Helvetica")
          .fillColor("#444444")
          .text(trimmed, {
            lineGap: 4,
          });
      }
    });

    // ── FOOTER ───────────────────────────────────────────────
    doc.moveDown(2);
    doc
      .fontSize(9)
      .font("Helvetica")
      .fillColor("#999999")
      .text("Generated by Minute Writer AI", { align: "center" });

    // Finalize the PDF — this triggers the 'end' event above
    doc.end();
  });
}

module.exports = { generatePDF };